### ISSUE TITLE
Using $regex in col:find() ?

### ISSUE THREAD

**Issue by sunao-uehara** [Olivine-Labs/resty-mongol#9]
Is there any way to use $regex search with col:find() or col:find_one() ?

mongo cli supports regex search as below.
```
db.collection.find( { "name" : { $regex : /Andrew/i } } );
```

But it doesn't work, if I do like this with resty-mongol's col:find_one().
```
col:find_one({name = {$regex: /Andrew/i }})
```

**Comment by DorianGray** [comment]
Yes, you can. your code should look something like...

```
col:find_one({name = {['$regex'] = 'Andrew', ['$options'] = 'i'}})
```

mongo-cli uses javascript, which has a regex type. Lua does not. Since JSON doesn't either, mongo's wire protocol represents regexes in the form above instead of the more terse /Andrew/i format.

...now that I think about it, I believe this format is documented in https://docs.mongodb.org/v3.0/reference/operator/query/regex/`

**Comment by sunao-uehara** [comment]
Thanks!! It works perfectly.
